# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.api.request_listener:
         class: AppBundle\EventListener\ApiRequestListener
         arguments: ["@serializer"]
         tags:
             - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

      app.api.exception_listener:
         class: AppBundle\EventListener\ExceptionListener
         tags:
             - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

      app.validator.duplicate_email:
         class: AppBundle\Validator\DuplicateEmailConstraintValidator
         arguments: [ "@doctrine.orm.entity_manager" ]
         tags:
              - { name: validator.constraint_validator, alias: duplicate_email_validator }

      app.corporation.subscriber:
          class: AppBundle\EventListener\CorporationListener
          arguments: [ "@security.token_storage" , "@tarioch.pheal.factory" ]
          tags:
              - { name: doctrine.event_subscriber, connection: default }
