services:
  evedata.registry:
    class: EveBundle\Repository\Registry

  evedata.repo.invflags:
    class: EveBundle\Repository\InvFlagRepository
    arguments: [ "@doctrine.dbal.eve_data_connection" ]
    tags:
        - { name: evedata.repository }

  evedata.repo.stastations:
    class: EveBundle\Repository\StaStationsRepository
    arguments: [ "@doctrine.dbal.eve_data_connection" ]
    tags:
        - { name: evedata.repository }

  evedata.repo.itemtypes:
    class: EveBundle\Repository\ItemTypeRepository
    arguments: [ "@doctrine.dbal.eve_data_connection" ]
    tags:
        - { name: evedata.repository }

  evedata.repo.regions:
    class: EveBundle\Repository\RegionRepository
    arguments: [ "@doctrine.dbal.eve_data_connection" ]
    tags:
        - { name: evedata.repository }

  evedata.repo.constellations:
    class: EveBundle\Repository\ConstellationRepository
    arguments: [ "@doctrine.dbal.eve_data_connection" ]
    tags:
        - { name: evedata.repository }

  evedata.repo.solarsystem:
    class: EveBundle\Repository\SolarSystemRepository
    arguments: [ "@doctrine.dbal.eve_data_connection" ]
    tags:
        - { name: evedata.repository }

  evedata.repo.invmarketgroups:
    class: EveBundle\Repository\InvMarketGroupRepository
    arguments: [ "@doctrine.dbal.eve_data_connection" ]
    tags:
        - { name: evedata.repository }
