
services:
  # Security  Voters
  security.access.corporation_voter:
      class:      AppBundle\Security\Authorization\Voter\CorporationVoter
      arguments: [ '@doctrine' ]
      public:     false
      tags:
          - { name: security.voter }

  security.access.character_voter:
      class:      AppBundle\Security\Authorization\Voter\CharacterVoter
      arguments: [ '@doctrine' ]
      public:     false
      tags:
          - { name: security.voter }

  # Api Listeners
  app.api.request_listener:
     class: AppBundle\EventListener\ApiRequestListener
     arguments: ["@serializer"]
     tags:
         - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.api.exception_listener:
     class: AppBundle\EventListener\ExceptionListener
     tags:
         - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  app.user.request_listener:
     class: AppBundle\EventListener\ActiveApiRequestListener
     arguments: [ "@security.token_storage", "@router", "@session", "@logger", "@doctrine" ]
     tags:
         - { name: kernel.event_listener, event: kernel.request, method: onRequest }


  # Doctrine Subscribers
  app.corporation.subscriber:
      class: AppBundle\EventListener\CorporationSubscriber
      arguments: [ "@security.token_storage" ]
      tags:
          - { name: doctrine.event_subscriber, connection: default }

  app.api_credentials.subscriber:
      class: AppBundle\EventListener\ApiCredentialsSubscriber
      arguments: [ "@security.token_storage" ]
      tags:
          - { name: doctrine.event_subscriber, connection: default }

  app.user.subscriber:
      class: AppBundle\EventListener\UserSubscriber
      arguments: [ "@app.character.manager", "@session" ]
      tags:
          - { name: doctrine.event_subscriber, connection: default }

  # Dispatchers
  app.task.dispatcher:
      class: AppBundle\EventListener\Dispatcher


  # Task Events
  app.task.coporation.new:
      class: AppBundle\EventListener\Corporation\NewCorporationListener
      arguments: [ "@app.evedataupdate.service", "@doctrine.orm.entity_manager" ]
      tags:
          - { name: app.task.subscriber }

  # this is probably going to be depricated
  app.task.belated_listener:
      class: AppBundle\EventListener\BelatedTaskListener
      arguments: [ "@app.task.dispatcher" ]
      tags:
        - { name: kernel.event_subscriber }

  # Validators
  app.validator.duplicate_email:
     class: AppBundle\Validator\DuplicateEmailConstraintValidator
     arguments: [ "@doctrine.orm.entity_manager" ]
     tags:
          - { name: validator.constraint_validator, alias: duplicate_email_validator }
  #registries
  app.evedata.registry:
    class: AppBundle\Service\DataManagerRegistry

  # Manager

  app.corporation.manager:
      arguments: [ "@tarioch.pheal.factory" , "@doctrine", "@evedata.registry", "@app.apikey.manager", "@logger" ]
      class: AppBundle\Service\DataManager\CorporationManager
      tags:
        - { name: eve.manager }

  app.markettransaction.manager:
      arguments: [ "@tarioch.pheal.factory" , "@doctrine","@evedata.registry",  "@logger" ]
      class: AppBundle\Service\DataManager\MarketTransactionManager
      tags:
        - { name: eve.manager }

  app.journaltransaction.manager:
      arguments: [ "@tarioch.pheal.factory", "@doctrine", "@evedata.registry", "@logger" ]
      class: AppBundle\Service\DataManager\JournalTransactionManager
      tags:
        - { name: eve.manager }

  app.apikey.manager:
      arguments: [ "@tarioch.pheal.factory" , "@doctrine", "@evedata.registry", "@logger" ]
      class: AppBundle\Service\DataManager\ApiKeyManager
      tags:
        - { name: eve.manager }

  app.account.manager:
      arguments: [ "@tarioch.pheal.factory", "@doctrine", "@evedata.registry", "@logger" ]
      class: AppBundle\Service\DataManager\AccountManager
      tags:
        - { name: eve.manager }

  app.character.manager:
      arguments: [ "@logger", "@app.apikey.manager" ]
      class: AppBundle\Service\DataManager\CharacterManager
      # @TODO Remove me when im implemented correctly
      #tags:
      #  - { name: eve.manager }

  app.starbase.manager:
      arguments: [ "@tarioch.pheal.factory" , "@doctrine", "@evedata.registry", "@logger" ]
      class: AppBundle\Service\DataManager\StarbaseManager
      tags:
        - { name: eve.manager }

  app.marketorder.manager:
      arguments: [ "@tarioch.pheal.factory" , "@doctrine", "@evedata.registry", "@logger" ]
      class: AppBundle\Service\DataManager\MarketOrderManager
      tags:
        - { name: eve.manager }

  app.reftype.manager:
      arguments: [ "@tarioch.pheal.factory" , "@doctrine", "@evedata.registry", "@logger" ]
      class: AppBundle\Service\DataManager\RefTypeManager
      tags:
        - { name: eve.manager }

  app.conquerable_station.manager:
      arguments: [ "@tarioch.pheal.factory" , "@doctrine", "@evedata.registry", "@logger" ]
      class: AppBundle\Service\DataManager\ConquerableStationManager
      tags:
        - { name: eve.manager }

  app.asset.manager:
      arguments: [ "@tarioch.pheal.factory", "@doctrine", "@evedata.registry", "@logger","@app.itemdetail.manager", "@app.price.manager" ]
      class: AppBundle\Service\DataManager\AssetManager
      tags:
        - { name: eve.manager }

  app.price.manager:
      arguments: [ "@doctrine" ]
      class: AppBundle\Service\PriceUpdateManager

  app.itemdetail.manager:
      arguments: [ "@evedata.registry" , "@doctrine"]
      class: AppBundle\Service\AssetDetailUpdateManager

  app.evedataupdate.service:
      arguments: [ "@app.evedata.registry", "@doctrine", "@logger"]
      class: AppBundle\Service\EveDataUpdateService


